### ISSUE TITLE
Escape usernames for #records messages

### ISSUE THREAD

**Issue by Scrumplex** [ddnet/ddnet-discordbot#15]
Today (04/11/2020) a message in `#records` has been posted which included the username `@everyone` (See [message](https://discord.com/channels/252358080522747904/338779500085116938/773536549383438357)). I am pretty sure that other types of formatting would be possible (i.e. markdown), which is why the usernames in these messages should be escaped from markdown.

**Comment by 12pm** [comment]
not part of the repo
