### ISSUE TITLE
bot doesn't respond on `/about`

### ISSUE THREAD

**Issue by AssassinTee** [ddnet/ddnet-discordbot#86]
Bot seems to not respond (=crash?) on `/about`:

![Unbenannt](https://github.com/user-attachments/assets/506c5317-5b9e-4f1a-a232-bd042db8d0e2)

**Comment by BlaiZephyr** [comment]
![image](https://github.com/user-attachments/assets/85433196-007b-4d79-ac78-c63c95a9660f)

this happens with every command from time to time - works now.

**Comment by AssassinTee** [comment]
hmm, now it works!
